<a href="https://colab.research.google.com/github/AivinBinoy/AivinBinoy/blob/main/task_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Load dataset
df = pd.read_csv("fitness_activity_100+_preprocess.csv")

# View data
print(df.head())

  User_ID  Steps_Per_Day  Calories_Burned  Workout_Minutes
0      U1           9270              581               91
1      U2          17795              735              119
2      U3           2860              341               17
3      U4           7390              381              117
4      U5          15418              449               84

In [ ]:
# Select numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64'])

print(numeric_cols.head())

   Steps_Per_Day  Calories_Burned  Workout_Minutes
0           9270              581               91
1          17795              735              119
2           2860              341               17
3           7390              381              117
4          15418              449               84

# **Standard Scaling (Z-score Normalization)**

👉 Formula:

Z=
(X−μ)/σ
	​

In [ ]:
scaler_standard = StandardScaler()

standard_scaled = scaler_standard.fit_transform(numeric_cols)

standard_df = pd.DataFrame(standard_scaled, columns=numeric_cols.columns)

print(standard_df.head())

   Steps_Per_Day  Calories_Burned  Workout_Minutes
0      -0.159517         0.183726         0.678568
1       1.722954         0.920927         1.543380
2      -1.574958        -0.965159        -1.607006
3      -0.574654        -0.773678         1.481608
4       1.198071        -0.448161         0.462365

In [ ]:
standard_df.describe()

       Steps_Per_Day  Calories_Burned  Workout_Minutes
count   1.000000e+02     1.000000e+02     1.000000e+02
mean    1.199041e-16    -3.552714e-17    -3.108624e-17
std     1.005038e+00     1.005038e+00     1.005038e+00
min    -1.723127e+00    -1.716721e+00    -1.668778e+00
25%    -8.971028e-01    -7.916293e-01    -8.889031e-01
50%     2.541833e-02     9.037891e-02     4.540262e-02
75%     7.312069e-01     8.862208e-01     9.642652e-01
max     1.750557e+00     1.705998e+00     1.543380e+00

In [ ]:
standard_df.describe()

       Steps_Per_Day  Calories_Burned  Workout_Minutes
count   1.000000e+02     1.000000e+02     1.000000e+02
mean    1.199041e-16    -3.552714e-17    -3.108624e-17
std     1.005038e+00     1.005038e+00     1.005038e+00
min    -1.723127e+00    -1.716721e+00    -1.668778e+00
25%    -8.971028e-01    -7.916293e-01    -8.889031e-01
50%     2.541833e-02     9.037891e-02     4.540262e-02
75%     7.312069e-01     8.862208e-01     9.642652e-01
max     1.750557e+00     1.705998e+00     1.543380e+00

### Standard Scaling Observations

After applying Standard Scaling, the data is transformed such that its mean is very close to 0 and its standard deviation is very close to 1. This is evident from the `describe()` output for `standard_df`.

- **Mean**: The `mean` for each column is approximately `1.199e-16`, `-3.552e-17`, and `-3.108e-17` respectively, which are all extremely close to zero.
- **Standard Deviation**: The `std` for each column is `1.005038e+00`, which is very close to 1.
- **Range**: The range of values is not fixed; it depends on the original data's distribution. Outliers will still be present and can significantly affect the scaled values, pushing them further from the mean.

# **Min-Max Scaling (Normalization)**

👉 Formula:

X'=
(X-Xmin)/
X max - X min

In [ ]:
scaler_minmax = MinMaxScaler()

minmax_scaled = scaler_minmax.fit_transform(numeric_cols)

# Convert to DataFrame
minmax_df = pd.DataFrame(minmax_scaled, columns=numeric_cols.columns)

print(minmax_df.head())

   Steps_Per_Day  Calories_Burned  Workout_Minutes
0       0.450130         0.555245         0.730769
1       0.992054         0.770629         1.000000
2       0.042655         0.219580         0.019231
3       0.330621         0.275524         0.980769
4       0.840951         0.370629         0.663462

In [ ]:
minmax_df.describe()

       Steps_Per_Day  Calories_Burned  Workout_Minutes
count     100.000000       100.000000       100.000000
mean        0.496052         0.501566         0.519519
std         0.289329         0.293637         0.312886
min         0.000000         0.000000         0.000000
25%         0.237795         0.270280         0.242788
50%         0.503369         0.527972         0.533654
75%         0.706551         0.760490         0.819712
max         1.000000         1.000000         1.000000

### Min-Max Scaling Observations

Min-Max Scaling transforms the data to a fixed range, typically between 0 and 1. This is confirmed by the `describe()` output for `minmax_df`.

- **Minimum**: The `min` for all columns is `0.000000`.
- **Maximum**: The `max` for all columns is `1.000000`.
- **Range**: All scaled values now lie strictly between 0 and 1.
- **Impact of Outliers**: While the values are squeezed into a specific range, Min-Max scaling is sensitive to outliers. A single large outlier can compress the majority of the data into a very small range, reducing the effectiveness of the scaling for the bulk of the data points.

In [ ]:
print("Standard Scaling Summary:\n", standard_df.describe())
print("\nMin-Max Scaling Summary:\n", minmax_df.describe())

Standard Scaling Summary:
        Steps_Per_Day  Calories_Burned  Workout_Minutes
count   1.000000e+02     1.000000e+02     1.000000e+02
mean    1.199041e-16    -3.552714e-17    -3.108624e-17
std     1.005038e+00     1.005038e+00     1.005038e+00
min    -1.723127e+00    -1.716721e+00    -1.668778e+00
25%    -8.971028e-01    -7.916293e-01    -8.889031e-01
50%     2.541833e-02     9.037891e-02     4.540262e-02
75%     7.312069e-01     8.862208e-01     9.642652e-01
max     1.750557e+00     1.705998e+00     1.543380e+00

Min-Max Scaling Summary:
        Steps_Per_Day  Calories_Burned  Workout_Minutes
count     100.000000       100.000000       100.000000
mean        0.496052         0.501566         0.519519
std         0.289329         0.293637         0.312886
min         0.000000         0.000000         0.000000
25%         0.237795         0.270280         0.242788
50%         0.503369         0.527972         0.533654
75%         0.706551         0.760490         0.819712
max         1.000000         1.000000         1.000000

### Comparison and Key Differences

Both Standard Scaling and Min-Max Scaling are common normalization techniques, but they differ in their approach and impact on the data:

1.  **Range of Values**:
    *   **Standard Scaling**: Transforms data to have a mean of 0 and a standard deviation of 1. The resulting values do not have a fixed range.
    *   **Min-Max Scaling**: Transforms data to a fixed range, typically 0 to 1. The minimum value becomes 0, and the maximum value becomes 1.

2.  **Sensitivity to Outliers**:
    *   **Standard Scaling**: Less affected by outliers than Min-Max scaling. Outliers will still exist but do not compress the rest of the data into a smaller range as much.
    *   **Min-Max Scaling**: Highly sensitive to outliers. Extreme values can disproportionately affect the scaling, leading to most of the data points being compressed into a narrow interval, which might reduce the effectiveness of distinguishing between them.

3.  **Use Cases**:
    *   **Standard Scaling**: Often preferred when the algorithm assumes a Gaussian distribution or when algorithms like SVM, Logistic Regression, or Neural Networks are used, where features with larger variances might dominate.
    *   **Min-Max Scaling**: Useful when the data needs to be within a specific range (e.g., for image processing, neural networks with sigmoid activation functions, or algorithms that don't assume any distribution of the data).

In this analysis, we can clearly see the distinct characteristics in the `describe()` outputs: Standard Scaling provides values centered around zero, while Min-Max Scaling provides values bounded between 0 and 1.