<a href="https://colab.research.google.com/github/AivinBinoy/AivinBinoy/blob/main/Tasl_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Age': [25, 30, np.nan, 45, 50, np.nan, 35],
    'Blood_Pressure': [120, np.nan, 130, 140, np.nan, 135, 128],
    'Cholesterol': [200, 220, np.nan, 240, 230, np.nan, 210],
    'Gender': ['M', 'F', 'F', np.nan, 'M', 'F', np.nan]
}

df = pd.DataFrame(data)
df

    Age  Blood_Pressure  Cholesterol Gender
0  25.0           120.0        200.0      M
1  30.0             NaN        220.0      F
2   NaN           130.0          NaN      F
3  45.0           140.0        240.0    NaN
4  50.0             NaN        230.0      M
5   NaN           135.0          NaN      F
6  35.0           128.0        210.0    NaN

## 🔍 Dataset Inspection
Checking structure and missing values

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             5 non-null      float64
 1   Blood_Pressure  5 non-null      float64
 2   Cholesterol     5 non-null      float64
 3   Gender          5 non-null      object
dtypes: float64(3), object(1)
memory usage: 356.0+ bytes

Age               2
Blood_Pressure    2
Cholesterol       2
Gender            2
dtype: int64

## 📌 Mean Imputation
Replacing missing values using mean (for numerical columns)

In [4]:
df_mean = df.copy()

df_mean['Age'].fillna(df_mean['Age'].mean(), inplace=True)
df_mean['Blood_Pressure'].fillna(df_mean['Blood_Pressure'].mean(), inplace=True)
df_mean['Cholesterol'].fillna(df_mean['Cholesterol'].mean(), inplace=True)

df_mean
df_mean.describe()

/tmp/ipykernel_18513/2026264338.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mean['Age'].fillna(df_mean['Age'].mean(), inplace=True)
/tmp/ipykernel_18513/2026264338.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mean['Blood_Pressure'].fillna(df_mean['Blood_Pressure'].mean(), inplace=True)
/tmp/ipykernel_18513/2026264338.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mean['Cholesterol'].fillna(df_mean['Cholesterol'].mean(), inplace=True)

             Age  Blood_Pressure  Cholesterol
count   7.000000         7.00000     7.000000
mean   37.000000       130.60000   220.000000
std     8.465617         6.15359    12.909944
min    25.000000       120.00000   200.000000
25%    32.500000       129.00000   215.000000
50%    37.000000       130.60000   220.000000
75%    41.000000       132.80000   225.000000
max    50.000000       140.00000   240.000000

## 📌 Median Imputation
Replacing missing values using median

In [5]:
df_median = df.copy()

df_median['Age'].fillna(df_median['Age'].median(), inplace=True)
df_median['Blood_Pressure'].fillna(df_median['Blood_Pressure'].median(), inplace=True)
df_median['Cholesterol'].fillna(df_median['Cholesterol'].median(), inplace=True)

df_median
df_median.describe()

/tmp/ipykernel_18513/157657316.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_median['Age'].fillna(df_median['Age'].median(), inplace=True)
/tmp/ipykernel_18513/157657316.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_median['Blood_Pressure'].fillna(df_median['Blood_Pressure'].median(), inplace=True)
/tmp/ipykernel_18513/157657316.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_median['Cholesterol'].fillna(df_median['Cholesterol'].median(), inplace=True)

             Age  Blood_Pressure  Cholesterol
count   7.000000        7.000000     7.000000
mean   36.428571      130.428571   220.000000
std     8.521681        6.160550    12.909944
min    25.000000      120.000000   200.000000
25%    32.500000      129.000000   215.000000
50%    35.000000      130.000000   220.000000
75%    40.000000      132.500000   225.000000
max    50.000000      140.000000   240.000000

## 📌 Mode Imputation
Replacing missing values in categorical column

In [6]:
df_mode = df.copy()

df_mode['Gender'].fillna(df_mode['Gender'].mode()[0], inplace=True)

df_mode
df_mode['Gender'].value_counts()

/tmp/ipykernel_18513/524040990.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_mode['Gender'].fillna(df_mode['Gender'].mode()[0], inplace=True)

Gender
F    5
M    2
Name: count, dtype: int64

## 📊 Comparison of Imputation Methods

In [7]:
print("Mean Imputation:\n", df_mean.describe())
print("\nMedian Imputation:\n", df_median.describe())

Mean Imputation:
              Age  Blood_Pressure  Cholesterol
count   7.000000         7.00000     7.000000
mean   37.000000       130.60000   220.000000
std     8.465617         6.15359    12.909944
min    25.000000       120.00000   200.000000
25%    32.500000       129.00000   215.000000
50%    37.000000       130.60000   220.000000
75%    41.000000       132.80000   225.000000
max    50.000000       140.00000   240.000000

Median Imputation:
              Age  Blood_Pressure  Cholesterol
count   7.000000        7.000000     7.000000
mean   36.428571      130.428571   220.000000
std     8.521681        6.160550    12.909944
min    25.000000      120.000000   200.000000
25%    32.500000      129.000000   215.000000
50%    35.000000      130.000000   220.000000
75%    40.000000      132.500000   225.000000
max    50.000000      140.000000   240.000000

## 🔍 Observations

- Mean imputation changes the average values slightly and is sensitive to outliers.
- Median imputation is more stable and not affected by extreme values.
- Mode imputation fills categorical data using the most frequent value.

### 📌 Key Differences:
- Mean shifts distribution if outliers exist
- Median keeps distribution balanced
- Mode maintains category frequency

## ✅ When to Use Each Method

- **Mean**: When data is normally distributed and no outliers
- **Median**: When data has outliers or skewed distribution
- **Mode**: For categorical data

## 🧾 Conclusion

All three imputation techniques were applied and compared.  
Median imputation proved more robust for numerical data with missing values, while mode was effective for categorical data.  
Proper selection of imputation method is important to maintain data integrity.